export const initialMenuItems = [
  // ☕ Coffee & Drinks
  {
    id: "mb-1",
    name: "Cappuccino",
    category: "Coffee & Drinks",
    price: 220,
    rating: 4.9,
    reviewsCount: 142,
    calories: 120,
    caffeine: "150mg",
    isSpecial: true,
    isPopular: true,
    dietary: ["Vegetarian"],
    description: "Traditional Italian double espresso topped with equal parts steamed milk and dense velvety microfoam, lightly dusted with Belgian cocoa.",
    image: "https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&w=800&q=80",
    tags: ["Hot", "Velvety Foam", "Cocoa Dusted"],
    accentColor: "#f97316",
    ingredients: ["Double Espresso", "Steamed Milk", "Velvet Foam", "Belgian Cocoa"]
  },
  {
    id: "mb-2",
    name: "Café Latte",
    category: "Coffee & Drinks",
    price: 240,
    rating: 4.85,
    reviewsCount: 118,
    calories: 160,
    caffeine: "140mg",
    isSpecial: false,
    isPopular: true,
    dietary: ["Vegetarian"],
    description: "Smooth, velvety steamed milk poured gently over a rich double shot of dark roasted espresso with delicate artisan latte art.",
    image: "https://images.unsplash.com/photo-1570968915860-54d5c301fa9f?auto=format&fit=crop&w=800&q=80",
    tags: ["Hot / Iced", "Smooth", "Latte Art"],
    accentColor: "#d97706",
    ingredients: ["Dark Roast Espresso", "Steamed Whole Milk", "Microfoam"]
  },
  {
    id: "mb-3",
    name: "Caramel Macchiato",
    category: "Coffee & Drinks",
    price: 280,
    rating: 4.95,
    reviewsCount: 184,
    calories: 240,
    caffeine: "150mg",
    isSpecial: true,
    isPopular: true,
    dietary: ["Vegetarian"],
    description: "Freshly steamed vanilla-infused milk marked with bold espresso shots and topped with our signature buttery caramel drizzle.",
    image: "https://images.unsplash.com/photo-1485808191679-5f86510681a2?auto=format&fit=crop&w=800&q=80",
    tags: ["Signature Brew", "Sweet & Rich", "Caramel Drizzle"],
    accentColor: "#f59e0b",
    ingredients: ["Espresso", "Steamed Milk", "Vanilla Syrup", "Caramel Drizzle"]
  },
  {
    id: "mb-4",
    name: "Cold Coffee",
    category: "Coffee & Drinks",
    price: 210,
    rating: 4.88,
    reviewsCount: 160,
    calories: 220,
    caffeine: "160mg",
    isSpecial: false,
    isPopular: true,
    dietary: ["Vegetarian"],
    description: "Classic thick and creamy blended chilled coffee prepared with rich espresso, vanilla ice cream, and chilled milk, served over crushed ice.",
    image: "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=800&q=80",
    tags: ["Chilled", "Creamy", "Ice Cream Blended"],
    accentColor: "#3b82f6",
    ingredients: ["Espresso Extract", "Chilled Milk", "Vanilla Bean Ice Cream", "Chocolate Swirl"]
  },
  {
    id: "mb-5",
    name: "Iced Americano",
    category: "Coffee & Drinks",
    price: 190,
    rating: 4.8,
    reviewsCount: 95,
    calories: 15,
    caffeine: "200mg",
    isSpecial: false,
    isPopular: false,
    dietary: ["Vegan", "Gluten-Free"],
    description: "Intense double espresso shots pulled directly over crystal clear ice and cold filtered mineral water for a crisp, refreshing coffee punch.",
    image: "https://images.unsplash.com/photo-1551030173-122aabc4489c?auto=format&fit=crop&w=800&q=80",
    tags: ["Crisp & Bold", "Zero Sugar", "High Caffeine"],
    accentColor: "#78350f",
    ingredients: ["Double Espresso", "Chilled Mineral Water", "Crystal Ice"]
  },
  {
    id: "mb-6",
    name: "Oreo Milkshake",
    category: "Coffee & Drinks",
    price: 260,
    rating: 4.96,
    reviewsCount: 220,
    calories: 380,
    caffeine: "10mg",
    isSpecial: true,
    isPopular: true,
    dietary: ["Vegetarian"],
    description: "Decadent thick milkshake blended with crunchy Oreo cookies, dark chocolate fudge drizzle, vanilla gelato, and whipped cream.",
    image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=800&q=80",
    tags: ["Thick Shake", "Oreo Crunch", "Chocolate Drizzle"],
    accentColor: "#ec4899",
    ingredients: ["Oreo Cookies", "Vanilla Gelato", "Fresh Whole Milk", "Dark Chocolate Fudge", "Whipped Cream"]
  },

  // 🍔 Café Food
  {
    id: "mb-7",
    name: "Chicken Burger",
    category: "Café Food",
    price: 290,
    rating: 4.92,
    reviewsCount: 215,
    calories: 540,
    caffeine: "0mg",
    isSpecial: true,
    isPopular: true,
    dietary: ["Non-Veg"],
    description: "Crispy herb-crusted golden chicken breast fillet with melted cheddar cheese, crisp lettuce, pickles, and smoky house sauce in a toasted brioche bun.",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80",
    tags: ["Chef Special", "Crispy Chicken", "Brioche Bun"],
    accentColor: "#ea580c",
    ingredients: ["Herb-Crusted Chicken", "Cheddar Cheese", "Brioche Bun", "Smoky Secret Sauce", "Crisp Lettuce"]
  },
  {
    id: "mb-8",
    name: "Veg Cheese Burger",
    category: "Café Food",
    price: 230,
    rating: 4.84,
    reviewsCount: 156,
    calories: 460,
    caffeine: "0mg",
    isSpecial: false,
    isPopular: true,
    dietary: ["Vegetarian"],
    description: "Grilled seasoned vegetable & potato patty layered with melted gouda cheese, crispy onion rings, sliced tomatoes, and creamy herb mayo.",
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80",
    tags: ["Cheesy", "Gourmet Veg", "Toasted Bun"],
    accentColor: "#84cc16",
    ingredients: ["Spiced Veggie Patty", "Melted Gouda Cheese", "Herb Mayo", "Tomatoes & Gherkins"]
  },
  {
    id: "mb-9",
    name: "Grilled Chicken Sandwich",
    category: "Café Food",
    price: 270,
    rating: 4.89,
    reviewsCount: 172,
    calories: 480,
    caffeine: "0mg",
    isSpecial: false,
    isPopular: true,
    dietary: ["Non-Veg"],
    description: "Tender peri-peri marinated grilled chicken slices, roasted bell peppers, melted mozzarella, and basil pesto in toasted artisanal multigrain bread.",
    image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=80",
    tags: ["Toasted Panini", "Peri-Peri", "Artisan Multigrain"],
    accentColor: "#10b981",
    ingredients: ["Grilled Chicken Fillet", "Basil Pesto", "Melted Mozzarella", "Multigrain Sourdough", "Roasted Peppers"]
  },
  {
    id: "mb-10",
    name: "French Fries",
    category: "Café Food",
    price: 160,
    rating: 4.94,
    reviewsCount: 310,
    calories: 320,
    caffeine: "0mg",
    isSpecial: false,
    isPopular: true,
    dietary: ["Vegan", "Vegetarian", "Gluten-Free"],
    description: "Crispy golden hand-cut Belgian-style potato fries seasoned with Himalayan pink salt and peri-peri herbs, served with garlic aioli dip.",
    image: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=800&q=80",
    tags: ["Crispy", "Peri-Peri Seasoned", "Aioli Dip"],
    accentColor: "#eab308",
    ingredients: ["Russet Potatoes", "Peri-Peri Seasoning", "Himalayan Pink Salt", "Garlic Aioli Dip"]
  },
  {
    id: "mb-11",
    name: "Chicken Pizza",
    category: "Café Food",
    price: 380,
    rating: 4.95,
    reviewsCount: 240,
    calories: 680,
    caffeine: "0mg",
    isSpecial: true,
    isPopular: true,
    dietary: ["Non-Veg"],
    description: "Hand-stretched sourdough pizza crust topped with rich San Marzano tomato sauce, smoky BBQ roasted chicken chunks, mozzarella, and fresh basil.",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80",
    tags: ["Woodfired Sourdough", "Smoky BBQ Chicken", "Extra Mozzarella"],
    accentColor: "#ef4444",
    ingredients: ["Sourdough Pizza Base", "Smoky BBQ Chicken", "Fresh Mozzarella", "San Marzano Sauce", "Basil Leaves"]
  },
  {
    id: "mb-12",
    name: "White Sauce Pasta",
    category: "Café Food",
    price: 310,
    rating: 4.91,
    reviewsCount: 198,
    calories: 510,
    caffeine: "0mg",
    isSpecial: true,
    isPopular: true,
    dietary: ["Vegetarian"],
    description: "Al dente penne tossed in rich velvety Alfredo white cream sauce with aged parmesan, sauteed garlic mushrooms, sweet corn, and Italian herbs.",
    image: "https://images.unsplash.com/photo-1645112411341-6c4fd023714a?auto=format&fit=crop&w=800&q=80",
    tags: ["Velvety Alfredo", "Aged Parmesan", "Garlic Mushrooms"],
    accentColor: "#06b6d4",
    ingredients: ["Penne Rigate", "Alfredo White Sauce", "Aged Parmesan", "Garlic Mushrooms", "Sweet Corn", "Oregano"]
  }
];

export const initialReviews = [
  {
    id: "rev-1",
    userName: "Elena Rostova",
    userAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
    rating: 5,
    date: "Yesterday",
    title: "Best Caramel Macchiato & Chicken Burger in the city!",
    comment: "The 3D interactive table booking made it so easy to secure our favorite window booth. The Caramel Macchiato is velvety and the Chicken Burger is wonderfully crispy!",
    tags: ["Perfect Crema", "Great Ambiance", "Juicy Burgers"],
    likes: 34
  },
  {
    id: "rev-2",
    userName: "Marcus Chen",
    userAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
    rating: 5,
    date: "3 days ago",
    title: "Incredible White Sauce Pasta & Oreo Shake",
    comment: "The pasta was so rich and creamy, and the Oreo Milkshake had the perfect thick texture. Ordering at the table was super smooth.",
    tags: ["Delicious Pasta", "Top Tier Shakes", "Great Tech"],
    likes: 21
  },
  {
    id: "rev-3",
    userName: "Sophia Lorenzi",
    userAvatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80",
    rating: 5,
    date: "1 week ago",
    title: "Their French Fries and Cappuccino are my daily go-to!",
    comment: "Crispy peri-peri fries paired with an authentic Viennese cappuccino. Love the cozy warm vibe and the friendly team.",
    tags: ["Crispy Fries", "Perfect Coffee", "Cozy Seating"],
    likes: 47
  }
];

export const initialReservations = [
  {
    id: "RES-9041",
    userName: "Alexander Wright",
    email: "alex.wright@example.com",
    phone: "+91 98765 43210",
    date: "2026-09-18",
    time: "10:30 AM",
    guests: 2,
    tableZone: "Sunlit Window Booth (Table #4)",
    occasion: "Casual Coffee & Catchup",
    specialRequests: "Near power outlet if possible",
    status: "Confirmed",
    createdAt: "2026-09-15T09:00:00Z"
  },
  {
    id: "RES-9042",
    userName: "Dr. Rachel Kim",
    email: "rachel.kim@example.com",
    phone: "+91 98123 45678",
    date: "2026-09-19",
    time: "02:00 PM",
    guests: 4,
    tableZone: "VIP Velvet Lounge (Table #8)",
    occasion: "Business Strategy Meeting",
    specialRequests: "Quiet corner with fast Wi-Fi",
    status: "Confirmed",
    createdAt: "2026-09-15T11:20:00Z"
  }
];

export const initialOrders = [
  {
    id: "MB-88210",
    userId: "cust-1",
    customerName: "Sarah Jenkins",
    customerEmail: "sarah.j@example.com",
    customerPhone: "+91 98765 12345",
    items: [
      {
        id: "mb-3",
        name: "Caramel Macchiato",
        price: 280,
        quantity: 2,
        size: "Regular",
        milk: "Whole Milk",
        sweetness: "75%",
        extraShots: 1,
        syrup: "Caramel"
      },
      {
        id: "mb-7",
        name: "Chicken Burger",
        price: 290,
        quantity: 1,
        size: "Standard",
        milk: "None",
        sweetness: "Regular",
        extraShots: 0,
        syrup: "None"
      }
    ],
    orderType: "Dine-In",
    deliveryAddress: "Table #4 (Sunlit Window Booth)",
    subtotal: 850,
    discount: 100,
    tax: 37,
    tip: 50,
    total: 837,
    paymentMethod: "UPI / Card",
    paymentStatus: "Paid",
    orderStatus: "Brewing",
    estimatedTime: "10-15 mins",
    createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString()
  }
];
